### ISSUE TITLE
Cannot connect to facebook

### ISSUE THREAD

**Issue by superfirefox** [rohit1290/Facebook-Login-1.9-1.12#5]
I report this bug:
1. Facebook SDK returned an error: Cross-site request forgery validation failed. The "state" param from the URL and session do not match.
   Errore fatale

Errore non previsto. Contatta l'amministratore indicando le seguenti informazioni:  

Exception #1455159657.

the good link:
https://www.facebook.com/v2.5/dialog/oauth?client_id=194152177589812&state=5c760496adf74d680fd2f70245c5b805&response_type=code&sdk=php-sdk-5.0.0&redirect_uri=http%3A%2F%2Far.vrexv.com%2Ffacebook_connect%2Flogin&scope=public_profile%2Cemail%2Cpublish_actions&auth_type=rerequest

the bad link:

https://www.facebook.com/v2.5/dialog/oauth?client_id=194152177589812&state=c4024ec7745e4e14e4d26c3cc3c944f4&response_type=code&sdk=php-sdk-5.0.0&redirect_uri=http%3A%2F%2Far.vrexv.com%2Ffacebook_connect%2Flogin&scope=public_profile%2Cemail%2Cpublish_actions&auth_type=rerequest

This two links should be the same!

**Comment by rohit1290** [comment]
Hi, Can you provide developer access of your facebook app to kraziest.hacker.90@gmail.com

**Comment by rohit1290** [comment]
Which version of elgg and facebook_connect are you using?

**Comment by superfirefox** [comment]
Hi, it's true that I am using versione 2.02 of Elgg.
The last versione of facebook connect.

If You connect using the "enter" botton of Aarlborg theme it works, but if
you use the module on the right of login does not work.

In other themes the "enter" botton has the same problem of the module.

The same problem if I use www.myelgg.com/login

however
http://ar.vrexv.com is my site.
You can test it, and see the problem.

Thanks

Adelperio

P.S.

I try To give you developer access (not so good in using facebook apps...
:-) let me found out..where it is the setting).

2016-02-11 5:22 GMT+01:00 TechBytes with Rohit notifications@github.com:

**Comment by superfirefox** [comment]
- fb says:
  -
- kraziest.hacker.90@gmail.com does not resolve to a valid user ID
  -

:-) So I think i need some other user-id for You.

2016-02-11 21:03 GMT+01:00 Adelperio de Negri de San Pietro <
flameoffirefox@gmail.com>:

**Comment by rohit1290** [comment]
Try my facebook ID kraziest.hacker@facebook.com

**Comment by superfirefox** [comment]
- kraziest.hacker@facebook.com does not resolve to a valid user ID

2016-02-11 22:29 GMT+01:00 TechBytes with Rohit notifications@github.com:

**Comment by rohit1290** [comment]
ok got it.. You need to enter my name, fbid or fb username. email ID won't work.

Just try "kraziest.hacker" it will work.. have tested it..

**Comment by rohit1290** [comment]
Hi, I was going through the app configuration. These are the changes that I have done:
1. Edited app domain from ar.vrexv.com to vrexv.com (No need to add sub-domain here)
2. Added http://ar.vrexv.com/facebook_connect/login to Valid OAuth redirect URIs

Now what I can see is that you have permission for only email, public_profile and user_friends and still your are calling the publish_actions request which is not on the approved list. Disable posting of facebook status and try again. Hopefully now it should work.

**Comment by rohit1290** [comment]
Closing the issue as I haven't heard from you for the past 2 days.

**Comment by superfirefox** [comment]
Sorry, I had time only today for looking after.

No, it seems the issue is still the same.

Do you mean to switch to "no"
here:
Want to post facebook account synched status on facebook for new users

or somewhere else?

2016-02-15 19:42 GMT+01:00 TechBytes with Rohit notifications@github.com:

**Comment by superfirefox** [comment]
for example, also from 
http://ar.vrexv.com/login  

it's impossibile to connect!

**Comment by rohit1290** [comment]
can you provide me with one admin account to your elgg setup and access to the source code for only facebook_connect folder in mod on your server?

**Comment by rohit1290** [comment]
I saw that you are using Elgg 2.0.2. I haven't released any plugin for that elgg version.
